#ifndef FINGERSLIST_H
#define FINGERSLIST_H
#include <QMap>
#include <QSet>
#include <QString>

enum E_FINGER_POSITION {
    FINTER_POSITION_UNKNOW_FINGER = 0,

    FINGER_POSITION_RIGHT_THUMB,
    FINGER_POSITION_RIGHT_INDEX,
    FINGER_POSITION_RIGHT_MIDDLE,
    FINGER_POSITION_RIGHT_RING,
    FINGER_POSITION_RIGHT_LITTLE,

    FINGER_POSITION_LEFT_THUMB,
    FINGER_POSITION_LEFT_INDEX,
    FINGER_POSITION_LEFT_MIDDLE,
    FINGER_POSITION_LEFT_RING,
    FINGER_POSITION_LEFT_LITTLE,

    FINGER_POSITION_RIGHT_FOUR = 13,
    FINGER_POSITION_LEFT_FOUR,
    FINGER_POSITION_BOTH_THUMBS,
    FINGER_POSITION_ANY_FINGER,
    FINGER_POSITION_SIZE,
};



struct UserTemplate {
    QMap<E_FINGER_POSITION, QByteArray> fingerTemplates;
    QSet<E_FINGER_POSITION> storedPositions;
    QString userName;
    int userID;
};
#endif // FINGERSLIST_H
