#ifndef MODES_H
#define MODES_H
enum E_TAB_TYPE {
    E_TAB_TYPE_CAPTURE = 0x00,
    E_TAB_TYPE_ENROLL = 0x01,
    E_TAB_TYPE_AUTH = 0x02,
    E_TAB_TYPE_VERIFICATION = 0x03
};

enum E_MODE_TYPE {
    E_MODE_LIVE,
    E_MODE_AUTO
};

enum E_MODE_ENROLLSTATUS {
    E_NEW_USER_NEW_FINGERPRINT_OK,
    E_NEW_USER_CONFLICT_WITH_ANOTHER_USER,
    E_OLD_USER_NEW_FINGERPRINT_OK,
    E_OLD_USER_REPEATED_FINGERPRINT,
    E_OVERWRITE_SUCESS,
    E_DATABASE_ERROR,
    E_NONE_STATUS
};

enum E_POPUP_TYPE {
    E_POPUP_TYPE_INFO,
    E_POPUP_TYPE_WARNING,
    E_POPUP_TYPE_SUCCESS
};

enum E_POPUP_BUTTON_TYPE{
    E_POPUP_BUTTON_TYPE_OK,
    E_POPUP_BUTTON_TYPE_YES_NO,
};

#endif // MODES_H
